# Generated by Django 2.0.6 on 2018-06-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='Property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Property'),
            preserve_default=False,
        ),
    ]
