# Generated by Django 2.0.6 on 2018-06-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180621_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Property_id',
            new_name='property_id',
        ),
    ]
