# Generated by Django 2.0.6 on 2018-06-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180621_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.Property'),
        ),
    ]
